import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiVite,
  SiNodedotjs,
  SiPython,
  SiPostgresql,
  SiExpress,
  SiMongodb,
  SiHtml5,
  SiCss,
  SiGit,
  SiGithub,
  SiNpm,
  SiVercel,
  SiPostman,
  SiFigma,
  SiOpenai,
  SiPytorch,
  SiHuggingface,
  SiFastapi,
  SiFramer,
  SiNetlify,
  SiJsonwebtokens,
  SiSocketdotio,
} from 'react-icons/si'
import { VscVscode } from 'react-icons/vsc'

const TECH_ICONS = {
  'React': SiReact,
  'TypeScript': SiTypescript,
  'JavaScript': SiJavascript,
  'Tailwind CSS': SiTailwindcss,
  'Vite': SiVite,
  'Node.js': SiNodedotjs,
  'Python': SiPython,
  'PostgreSQL': SiPostgresql,
  'Express': SiExpress,
  'MongoDB': SiMongodb,
  'HTML': SiHtml5,
  'CSS': SiCss,
  'HTML & CSS': SiHtml5,
  'Git': SiGit,
  'GitHub': SiGithub,
  'VS Code': VscVscode,
  'npm': SiNpm,
  'Vercel': SiVercel,
  'Postman': SiPostman,
  'Figma': SiFigma,
  'Figma API': SiFigma,
  'OpenAI API': SiOpenai,
  'PyTorch': SiPytorch,
  'Hugging Face': SiHuggingface,
  'FastAPI': SiFastapi,
  'Framer Motion': SiFramer,
  'Netlify': SiNetlify,
  'JWT': SiJsonwebtokens,
  'Socket.io': SiSocketdotio,
}

export function getTechIcon(label) {
  return TECH_ICONS[label] ?? null
}
